import type { Product, ProductCategory } from '@org/lib';

export const PRODUCT_CATEGORIES: ('All' | ProductCategory)[] = [
  'All',
  'Electronics',
  'Clothing',
  'Home & Kitchen',
  'Sports',
  'Beauty',
  'Books',
  'Furniture',
];

// Deterministic pseudo-random [0, 1) from integer seed
function h(n: number): number {
  const x = Math.sin(n * 9301 + 49297) * 233280;
  return x - Math.floor(x);
}

function pick<T>(arr: readonly T[], seed: number): T {
  return arr[Math.floor(h(seed) * arr.length)];
}

const BADGES = ['Best Seller', 'New', 'Sale', 'Top Rated', 'Popular'] as const;

type CategoryData = {
  adjectives: readonly string[];
  nouns: readonly string[];
  subtypes: readonly string[];
  minPrice: number;
  maxPrice: number;
  desc: (adj: string, noun: string, sub: string, n: number) => string;
};

const DESCRIPTIONS: Record<ProductCategory, readonly string[]> = {
  Electronics: [
    'noise cancellation and 30-hour battery life',
    'ultra-fast processor and stunning 4K display',
    'advanced connectivity and premium audio quality',
    'intelligent sensor technology and long-range performance',
    'lightning-fast response time and ergonomic design',
  ],
  Clothing: [
    'premium cotton blend for all-day comfort',
    'sustainable recycled materials with a modern fit',
    'high-performance moisture-wicking fabric',
    'natural breathable fibers for any season',
    'durable construction and timeless styling',
  ],
  'Home & Kitchen': [
    'one-touch operation and energy-efficient performance',
    'professional-grade materials for lasting durability',
    'precision temperature control and easy cleanup',
    'space-saving design with maximum capacity',
    'dishwasher-safe components and intuitive controls',
  ],
  Sports: [
    'superior grip and responsive cushioning',
    'lightweight carbon-fiber construction for peak performance',
    'moisture-wicking technology for intense training sessions',
    'ergonomic design that reduces fatigue during extended use',
    'durable materials built for outdoor conditions',
  ],
  Beauty: [
    'clinically tested formula with long-lasting results',
    'infused with botanical extracts for radiant skin',
    'dermatologist-approved and suitable for sensitive skin',
    'luxurious texture with a lightweight, non-greasy finish',
    'rich in antioxidants and hydrating ingredients',
  ],
  Books: [
    'a must-read bestseller with practical insights',
    'award-winning narrative that redefines the genre',
    'comprehensive guide praised by industry experts',
    'groundbreaking ideas presented in an accessible style',
    'richly illustrated with in-depth analysis',
  ],
  Furniture: [
    'kiln-dried hardwood frame with high-density foam cushions',
    'solid steel construction with a powder-coat finish',
    'sustainably sourced wood with hand-applied finish',
    'adjustable components for personalized comfort',
    'assembly-free design ready to use out of the box',
  ],
};

const CATEGORY_DATA: Record<ProductCategory, CategoryData> = {
  Electronics: {
    adjectives: [
      'Sony',
      'Apple',
      'Samsung',
      'LG',
      'Bose',
      'JBL',
      'Dell',
      'HP',
      'Lenovo',
      'Asus',
      'Acer',
      'Microsoft',
      'Google',
      'Razer',
      'Logitech',
      'Sennheiser',
      'Jabra',
      'Anker',
      'Belkin',
      'Corsair',
      'Creative',
      'Philips',
      'Panasonic',
      'Toshiba',
      'Sharp',
    ],
    nouns: [
      'Headphones',
      'Earbuds',
      'Speaker',
      'Monitor',
      'Laptop',
      'Tablet',
      'Keyboard',
      'Mouse',
      'Webcam',
      'Smartwatch',
      'Camera',
      'Drone',
      'Projector',
      'TV',
      'Router',
      'Hub',
      'Charger',
      'Power Bank',
      'Microphone',
      'Controller',
    ],
    subtypes: [
      'Pro',
      'Ultra',
      'Max',
      'Plus',
      'Elite',
      'Advanced',
      'Premium',
      'Lite',
      'Mini',
      'Portable',
      'Series X',
      'Gen 2',
      'Gen 3',
      'Turbo',
      'Neo',
      'Air',
      'Studio',
    ],
    minPrice: 19.99,
    maxPrice: 3999.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${noun} ${sub} featuring ${DESCRIPTIONS.Electronics[n % DESCRIPTIONS.Electronics.length]} for professional and everyday use.`,
  },
  Clothing: {
    adjectives: [
      'Nike',
      'Adidas',
      'Zara',
      "Levi's",
      'Ralph Lauren',
      'Tommy Hilfiger',
      'Calvin Klein',
      'Gucci',
      'Puma',
      'Under Armour',
      'The North Face',
      'Patagonia',
      'Uniqlo',
      'Gap',
      'H&M',
      'Versace',
      'Burberry',
      'Armani',
      'Balenciaga',
      'Off-White',
    ],
    nouns: [
      'T-Shirt',
      'Jacket',
      'Jeans',
      'Dress',
      'Hoodie',
      'Sneakers',
      'Boots',
      'Pants',
      'Shorts',
      'Coat',
      'Sweater',
      'Blouse',
      'Skirt',
      'Vest',
      'Cardigan',
      'Joggers',
      'Blazer',
      'Chinos',
      'Sandals',
      'Leggings',
    ],
    subtypes: [
      'Classic',
      'Slim Fit',
      'Regular Fit',
      'Relaxed',
      'Cropped',
      'Oversized',
      'Tailored',
      'Vintage',
      'Sport',
      'Casual',
      'Formal',
      'Urban',
      'Washed',
      'Printed',
      'Striped',
    ],
    minPrice: 9.99,
    maxPrice: 799.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} crafted from ${DESCRIPTIONS.Clothing[n % DESCRIPTIONS.Clothing.length]} — available in multiple colors and all sizes.`,
  },
  'Home & Kitchen': {
    adjectives: [
      'Nespresso',
      'Vitamix',
      'All-Clad',
      'Ninja',
      'Dyson',
      'KitchenAid',
      'Cuisinart',
      'Breville',
      'Lodge',
      'Le Creuset',
      'OXO',
      'Instant Pot',
      'Zwilling',
      'Wüsthof',
      'Fellow',
      'Philips',
      'Tefal',
      'Bosch',
      'Miele',
      'Weber',
    ],
    nouns: [
      'Blender',
      'Coffee Maker',
      'Air Fryer',
      'Vacuum',
      'Kettle',
      'Toaster',
      'Cookware Set',
      "Chef's Knife",
      'Cutting Board',
      'Storage Container',
      'Candle Set',
      'Throw Blanket',
      'Plant Pot',
      'Serving Bowl',
      'Baking Sheet',
      'Pressure Cooker',
      'Food Processor',
      'Dish Rack',
      'Spice Rack',
      'Kitchen Scale',
    ],
    subtypes: [
      'Stainless Steel',
      'Cast Iron',
      'Non-stick',
      'Bamboo',
      'Ceramic',
      'Copper',
      'Glass',
      'Silicone',
      'Pro',
      'Smart',
      'Digital',
      'Compact',
      'XL',
      'Premium',
      'Deluxe',
    ],
    minPrice: 14.99,
    maxPrice: 1299.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} with ${DESCRIPTIONS['Home & Kitchen'][n % DESCRIPTIONS['Home & Kitchen'].length]}.`,
  },
  Sports: {
    adjectives: [
      'Manduka',
      'Bowflex',
      'ASICS',
      'Trek',
      'Wilson',
      'Callaway',
      'Speedo',
      'Garmin',
      'Salomon',
      'Yeti',
      'Hydro Flask',
      'TRX',
      'Rogue',
      'Titleist',
      'Rawlings',
      'Schwinn',
      'Peloton',
      'Osprey',
      'Black Diamond',
      'Coleman',
    ],
    nouns: [
      'Yoga Mat',
      'Dumbbells',
      'Running Shoes',
      'Mountain Bike',
      'Tennis Racket',
      'Water Bottle',
      'Resistance Bands',
      'Foam Roller',
      'Jump Rope',
      'Kettlebell',
      'Backpack',
      'Sleeping Bag',
      'Tent',
      'Helmet',
      'Swim Goggles',
      'Golf Club Set',
      'Basketball',
      'Soccer Ball',
      'Fitness Tracker',
      'Pull-up Bar',
    ],
    subtypes: [
      'Performance',
      'Pro',
      'Elite',
      'Ultra',
      'Endurance',
      'Training',
      'Competition',
      'Outdoor',
      'All-Weather',
      'Lightweight',
      'Heavy-Duty',
      'Adjustable',
      'Advanced',
    ],
    minPrice: 9.99,
    maxPrice: 2499.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} engineered for ${DESCRIPTIONS.Sports[n % DESCRIPTIONS.Sports.length]}.`,
  },
  Beauty: {
    adjectives: [
      'La Mer',
      'Chanel',
      'Urban Decay',
      'Dyson',
      'Tatcha',
      'Charlotte Tilbury',
      'NARS',
      'MAC',
      'Fenty Beauty',
      'Lancôme',
      'Estée Lauder',
      "L'Oréal",
      'Clinique',
      'SK-II',
      'Drunk Elephant',
      'The Ordinary',
      "Paula's Choice",
      'Olaplex',
      'Moroccanoil',
      "Kiehl's",
    ],
    nouns: [
      'Moisturizer',
      'Serum',
      'Foundation',
      'Mascara',
      'Lipstick',
      'Eye Shadow Palette',
      'Perfume',
      'Hair Dryer',
      'Face Wash',
      'Toner',
      'Sunscreen',
      'Blush',
      'Concealer',
      'Hair Mask',
      'Body Lotion',
      'Exfoliator',
      'Setting Spray',
      'Nail Polish',
      'Eyebrow Pencil',
      'Contour Kit',
    ],
    subtypes: [
      'Luxury',
      'Hydrating',
      'Anti-aging',
      'Brightening',
      'Matte',
      'Glowing',
      'Natural',
      'Organic',
      'Vegan',
      'Travel Size',
      'Full Size',
      'Pro',
      'Intensive',
      'Gentle',
    ],
    minPrice: 8.99,
    maxPrice: 599.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} — ${DESCRIPTIONS.Beauty[n % DESCRIPTIONS.Beauty.length]}.`,
  },
  Books: {
    adjectives: [
      'Penguin',
      'HarperCollins',
      'Random House',
      'Simon & Schuster',
      'Macmillan',
      'Oxford',
      'Cambridge',
      'MIT Press',
      "O'Reilly",
      'Wiley',
      'Pearson',
      'Scholastic',
      'Chronicle',
      'Taschen',
      'Phaidon',
    ],
    nouns: [
      'Novel',
      'Memoir',
      'Cookbook',
      'Self-Help Guide',
      'Biography',
      'History Book',
      'Science Book',
      'Philosophy Text',
      'Art Book',
      'Business Book',
      'Poetry Collection',
      'Travel Guide',
      "Children's Book",
      'Graphic Novel',
      'Short Stories',
      'Reference Manual',
      'Textbook',
      'Atlas',
      'Encyclopedia',
      'Anthology',
    ],
    subtypes: [
      'Bestselling',
      'Award-Winning',
      'Definitive',
      'Illustrated',
      'Revised',
      'Expanded',
      "Collector's Edition",
      'Hardcover',
      'Paperback',
      'Annotated',
      'Complete',
      'Classic',
    ],
    minPrice: 7.99,
    maxPrice: 199.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} — ${DESCRIPTIONS.Books[n % DESCRIPTIONS.Books.length]}, praised by readers worldwide.`,
  },
  Furniture: {
    adjectives: [
      'IKEA',
      'West Elm',
      'Pottery Barn',
      'CB2',
      'Restoration Hardware',
      'Herman Miller',
      'Steelcase',
      'Ashley',
      'Article',
      'Floyd',
      'Burrow',
      'Interior Define',
      'Room & Board',
      'Design Within Reach',
      'Crate & Barrel',
    ],
    nouns: [
      'Sofa',
      'Coffee Table',
      'Office Chair',
      'Bookcase',
      'Bed Frame',
      'Dining Table',
      'Nightstand',
      'Dresser',
      'Desk',
      'Armchair',
      'Bookshelf',
      'TV Stand',
      'Bar Stool',
      'Side Table',
      'Ottoman',
      'Bench',
      'Cabinet',
      'Wardrobe',
      'Shelving Unit',
      'Sectional',
    ],
    subtypes: [
      'Mid-Century Modern',
      'Industrial',
      'Scandinavian',
      'Rustic',
      'Minimalist',
      'Contemporary',
      'Bohemian',
      'Traditional',
      'Farmhouse',
      'Coastal',
      'Urban',
      'Convertible',
      'Modular',
      'Compact',
    ],
    minPrice: 49.99,
    maxPrice: 4999.99,
    desc: (adj, noun, sub, n) =>
      `${adj} ${sub} ${noun} featuring ${DESCRIPTIONS.Furniture[n % DESCRIPTIONS.Furniture.length]} — ships fully packaged with assembly guide included.`,
  },
};

function generateProducts(): Product[] {
  const categories: ProductCategory[] = [
    'Electronics',
    'Clothing',
    'Home & Kitchen',
    'Sports',
    'Beauty',
    'Books',
    'Furniture',
  ];
  const total = 1_000_000;
  const products: Product[] = new Array(total);

  for (let i = 0; i < total; i++) {
    const id = i + 1;
    const s = id;
    const category = categories[i % categories.length];
    const data = CATEGORY_DATA[category];

    const adj = pick(data.adjectives, s * 7);
    const noun = pick(data.nouns, s * 11);
    const sub = pick(data.subtypes, s * 13);
    const variantNum = Math.floor(i / categories.length) + 1;

    const priceT = h(s * 17);
    const price =
      Math.round(
        (data.minPrice + priceT * (data.maxPrice - data.minPrice)) * 100,
      ) / 100;

    const hasDiscount = h(s * 19) > 0.5;
    const originalPrice = hasDiscount
      ? Math.round(price * (1.1 + h(s * 23) * 0.3) * 100) / 100
      : undefined;

    const rating = Math.round((3.0 + h(s * 29) * 2.0) * 10) / 10;
    const reviewCount = Math.floor(h(s * 31) * 50000) + 5;
    const inStock = h(s * 37) > 0.08;
    const image = `https://picsum.photos/seed/${id}/600/600`;
    const badge =
      h(s * 43) > 0.7 ? (pick(BADGES, s * 47) as string) : undefined;

    const product: Product = {
      id: String(id),
      name: `${adj} ${noun} ${sub} ${variantNum}`,
      price,
      category,
      description: data.desc(adj, noun, sub, variantNum),
      image,
      rating,
      reviewCount,
      inStock,
    };

    if (originalPrice !== undefined) product.originalPrice = originalPrice;
    if (badge !== undefined) product.badge = badge;

    products[i] = product;
  }

  return products;
}

export const PRODUCTS: Product[] = generateProducts();
